name: Basic Defaults Test

on:
  pull_request:
    branches: [ main ]

jobs:
  Basic_Defaults_Test_Job:
    runs-on: ari
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create cert file
      run: cat <<< "${{secrets.BASE_64_CERT}}" > my-cert.pem
    - name: Synopsys Detect
      uses: synopsys-sig/detect-action@main
      env:
        NODE_EXTRA_CA_CERTS: ./my-cert.pem
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.7.0
          blackduck-url: ${{ secrets.GK_BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.GK_BLACKDUCK_API_TOKEN }}
          fail-on-severities: ALL