# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Demo Workflow
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: demo-runner
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Create Black Duck Policy
      env:
        NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
      uses: blackducksoftware/create-policy-action@demo-version
      with:
        blackduck-url: ${{ secrets.TEST_BLACKDUCK_URL }}
        blackduck-api-token: ${{ secrets.TEST_BLACKDUCK_API_TOKEN }}
        policy-name: 'Demo Policy'
        policy-description: 'A description of the demo policy. It's pretty strict, but reasonable.'
        no-fail-if-policy-exists: true # If the policy exists, the workflow will do nothing.
        max-critical: 0
        max-high: 0
        max-medium: 3
        max-low: 10
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run Synopsys Detect
      uses: synopsys-sig/detect-action@no-fail-if-policy-exists
      env:
        NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.7.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
