name: Error Handling Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  Error_Handling_Job:
    runs-on: gavin
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create cert file
      run: echo "No cert. Oops :/"
    - name: Synopsys Detect
      uses: synopsys-sig/detect-action@gk-clean-up-logs
      env:
        NODE_EXTRA_CA_CERTS: ./my-cert.pem
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.7.0
          blackduck-url: ${{ secrets.GK_BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.GK_BLACKDUCK_API_TOKEN }}
