# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Simple Coverity Workflow
on: [pull_request]

jobs:
  build:
    runs-on: gavin
    env:
      COV_URL: ${{secrets.GK_COV_URL}}
      COV_USER: ${{secrets.GK_COV_USER}}
      COV_PASS: ${{secrets.GK_COV_PASS}}
    steps:
    - uses: actions/checkout@v2
    - name: Coverity Capture
      run: 'cov-capture --dir idir --project-dir .'
    - name: Coverity Analyze
      run: 'cov-analyze --dir idir --strip-path `pwd` --security-file ~/Downloads/license.dat'
    - name: Coverity Commit Defects
      run: cov-commit-defects --dir idir --security-file ~/Downloads/license.dat --url ${COV_URL} --on-new-cert trust --stream actions-playground-main --scm git --user ${COV_USER} --password ${COV_PASS}
    - name: Coverity Format Errors
      run: 'cov-format-errors --dir idir --json-output-v7 output.json --security-file ~/Downloads/license.dat'
    - name: Coverity Report
      uses: synopsys-sig/coverity-report-output-v7-json@gk-coverity-api
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        json-file-path: output.json
        coverity-url: ${{secrets.GK_COV_URL}}
        coverity-username: ${{secrets.GK_COV_USER}}
        coverity-password: ${{secrets.GK_COV_PASS}}
        coverity-project-name: actions-playground
