# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Simple Coverity Workflow
on: [pull_request]

jobs:
  build:
    runs-on: rich
    steps:
    - uses: actions/checkout@v2
    - name: Coverity Capture
      run: '${{ secrets.RO_COVERITY_PATH }}/cov-capture --dir idir --source-dir .'
    - name: Coverity Analyze
      run: '${{ secrets.RO_COVERITY_PATH }}/cov-analyze --dir idir'
    - name: Coverity Format Errors
      run: '${{ secrets.RO_COVERITY_PATH }}/cov-format-errors --dir idir --json-output-v7 output.json'
    - name: Coverity Report
      uses: synopsys-sig/coverity-report-output-v7-json@gk-coverity-api
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        json-file-path: output.json
